### ISSUE TITLE
Update to AMQP 1.0 and adding this library to official examples page

### ISSUE THREAD

**Issue by paulocoghi** [cloudamqp/amq-protocol.cr#5]
Hi!

I would like to suggest to update the library to AMQP 1.0, as well as adding it to the official examples page, here:
https://www.amqp.org/about/examples

Thanks!

**Comment by carlhoerberg** [comment]
Why do you suggest that? :) 1.0 is a competently different protocol from amqp 0-9-1 (and no way better imho).

**Comment by paulocoghi** [comment]
My fault :)

I do not know AMQP (I am planning on study some protocols for IoT, and use them on Crystal) and I assumed it followed semantic versioning and, therefore, was backward compatible.

In this case, in regard of being listed on the AMQP examples/libraries page, do you think this could be beneficial for the amq-protocol.cr project?

**Comment by carlhoerberg** [comment]
Ok! Then you might find these libs interesting too:

https://github.com/cloudamqp/amqp-client.cr/
https://github.com/84codes/mqtt-client.cr/

**Comment by paulocoghi** [comment]
Wow! Thanks a lot!
